apiVersion: v1
kind: Pod
metadata:
  name: color-api-pod
  namespace: dev
  labels:
    app: color-api
spec:
  containers:
  - name: color-api-container
    image: lmacademy/color-api:1.1.0
    resources:
      requests:
        cpu: '128m'
        memory: '128Mi'
      limits:
        memory: "500Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
