# kubectl get resourcequota -A
# kubectl get resourcequota dev-rq -n dev

apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-rq
  namespace: dev
spec:
  hard:
    requests.cpu: '1'
    requests.memory: '1Gi'
    limits.cpu: '2'
    limits.memory: '2Gi'