# kubectl get pv
# kubectl get pvc
# It has 1-1 relationship i.e, if a PV is bound to a claim it cannot be bound to another claim.
# resource created is available across pod and exists evn when pod is deleted.
# if we delete PVC, then PV status will be shown as released but can't be reassigned by creating resource back again. 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume
  namespace: default
  labels:
    name: persistent-vol
spec:
  storageClassName: local-storage
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/usr/local
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchKeyExpressions:
          - key: kubernetes.io.hostname
            operator: In
            value: ['minikube']
---
# it means give me a volume which matches below spec claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-claim
  namespace: default
  labels:
    name: persistent-volume-claim
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: Pod
metadata:
  name: local-vol-pod
  namespace: default
  labels:
    name: persistent-vol
spec:
  containers:
  - name: local-vol-container
    image: busybox:1.36.1
    command:
      - 'sh'
      - '-c'
      - 'sleep 3000'
    resources:
      limits:
        memory: "256Mi"
        cpu: "2"
      requests:
        cpu: "1"
        memory: '128Mi'
    volumeMounts:
      - name: local-volume
        mountPath: /mnt/local
    volumes:
      - name: local-volume
        persistentVolumeClaim:
          claimName: local-volume-claim
---
apiVersion: v1
kind: Pod
metadata:
  name: local-vol-pod2
  namespace: default
  labels:
    name: persistent-vol2
spec:
  containers:
  - name: local-vol-container2
    image: busybox:1.36.1
    command:
      - 'sh'
      - '-c'
      - 'sleep 3000'
    resources:
      limits:
        memory: "256Mi"
        cpu: "2"
      requests:
        cpu: "1"
        memory: '128Mi'
    volumeMounts:
      - name: local-volume
        mountPath: /mnt/local2
    volumes:
      - name: local-volume
        persistentVolumeClaim:
          claimName: local-volume-claim