# By default Strategy type is RollingUpdate
# kubectl get deploy
# kubectl describe deploy nginx-deployment
# roolout with undo cli: kubectl rollout undo deployment nginx-deployment
# adding annotation from cli: kubectl annotate deployment nginx-deployment "kubernetes.io/change-cause"="updated image from 1.27.0 to 1.27.1"
# scaling deployment from cli: kubectl scale deployment nginx-deployment --replicas=5
# check history: kubectl rollout history deployment nginx-deployment
# check status: kubectl rollout status deployment nginx-deployment
# types of deployment strategy: RollingUpdate, Recreate, Blue Green, Canary, A/B Testing, Shadow

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  annotations:
    "kubernetes.io/change-cause": "updated image from 1.27.0 to 1.27.1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.27.1
          ports:
            - containerPort: 80
