# Same as: kubectl run nginx --imae=nginx

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80

---
# Same as: kubectl expose pod nginx --type=NodePort --port-80
# Create yml template from CLI: kubectl expose pod nginx --type=NodePort --port-80 --dry-run=client -o yml

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-pod
