# Same as: kubectl expose pod nginx --type=NodePort --port-80
# Create yml template from CLI: kubectl expose pod nginx --type=NodePort --port-80 --dry-run=client -o yml
# type of service: ClusterIP, NodePort, LoadBalancer, ExternalName

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-pod
