apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  labels:
    app: config-map
spec:
  containers:
    - name: config-pod-container
      image: lmacademy/color-api:1.3.0
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: '1'
          memory: '128Mi'
        requests:
          cpu: '1'
          memory: '64Mi'
      # Directly import file but env name should match in src and configmap key
      # envFrom:
      #   - configMapRef:
      #       name: configMap
      env:
      - name: DEFAULT_COLOR
        valueFrom:
          configMapKeyRef:
            key: COLOR
            name: red-config