# ClusterIP gives a stable/static IP and distributes equal loads to all the pods mapped to it
# Exposes the Service on a cluster-internal IP. Choosing this value makes the Service only reachable from within the cluster.

apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-svc
  labels:
    app: color-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: color-api
