apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard # can be any name
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
