apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    app: deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy
  template:
    metadata:
    labels:
      app: deploy
    spec:
      containers:
        - name: deploy-container
          image: nginx
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-config-map
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD