apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-api-deploy
  labels:
    app: color-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: color-api
  template:
    metadata:
      labels:
        app: color-api
    spec:
      containers:
      - name: color-api-container
        image: lmacademy/color-api:1.2.1
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: '1'
            memory: '256Mi'
          limits:
            cpu: '2'
            memory: '512Mi'
        env:
          - name: DELAY_STARTUP
            value: 'false'
          - name: FAIL_LIVENESS
            value: 'true'
        startupProbe:
          httpGet:
            path: /health
            port: 80
          failureThreshold: 2
          periodSeconds: 3