apiVersion: v1
kind: Service
metadata:
  name: prod-headless-service
  namespace: prod-orders
  labels:
    app: production
spec:
  clusterIP: None
  selector:
    app: production
  ports:
    - port: 8080

# Headless Service:
#   No virtual IP
#   No load balancing
#   Creates DNS records per Pod