apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: dev
  labels:
    app: nginx-pod
spec:
  containers:
  - name: nginx-container
    image: lmacademy/color-api:1.1.0
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: dev
  labels:
    app: nginx-pod
spec:
  type: ClusterIP
  selector:
    app: nginx-pod
  ports:
  - port: 80
    targetPort: 80
