# kubectl create secret generic <secret_name> --from-literal=username=<username> --from-literal=password=<password>
# kubectl create secret generic db-creds --from-literal=username=db_user --from-literal=password=db_pass 

apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
  - name: busybox
    image: busybox:1.36.0
    # envFrom:
    #   - secretKeyRef:
    #       name: db-creds
    env:
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            key: username
            name: db-creds
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: db-creds
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "500m"

